name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled  # This can also trigger on other events like 'synchronize', 'opened', etc.
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name contains 'ready to merge'  # Check for a specific label

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge PR
        uses: "peter-evans/merge-pull-request@v3"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge  # Use 'merge', 'squash', or 'rebase'
          commit-title: 'Merge pull request #${{ github.event.pull_request.number }}'
          commit-message: 'Automated merge of pull request #${{ github.event.pull_request.number }} into main'
